consultant:
  anthropic:
    name: "Consultant"
    provider: "anthropic"
    model: "claude-3-5-sonnet-20241022"
    max_retries: 10000
    temperature: 0.2
  
  openai:
    name: "Consultant"
    provider: "openai"
    model: "gpt-4o"
    max_retries: 10000
    temperature: 0.2
  
  sglang:
    name: "Consultant"
    provider: "sglang"
    model: "Qwen/Qwen2.5-7B-Instruct"
    port: 30005
    max_retries: 10000
    temperature: 0.2
    
  azure:
    name: "Consultant"
    provider: "azure"
    model: "DeepSeek-R1"
    endpoint: "https://DeepSeek-R1-rgchv.eastus.models.ai.azure.com"
    max_retries: 10000
    temperature: 0.2

consultant_judge:
  anthropic:
    name: "Consultant Judge"
    provider: "anthropic"
    model: "claude-3-5-sonnet-20241022"
    max_retries: 10000
    temperature: 0
  
  openai:
    name: "Consultant Judge"
    provider: "openai"
    model: "gpt-4o"
    max_retries: 10000
    temperature: 0
  
  sglang:
    name: "Consultant Judge"
    provider: "sglang"
    model: "Qwen/Qwen2.5-7B-Instruct"
    port: 30005
    max_retries: 10000
    temperature: 0
  azure:
    name: "Consultant Judge"
    provider: "azure"
    model: "DeepSeek-R1"
    endpoint: "https://DeepSeek-R1-rgchv.eastus.models.ai.azure.com"
    max_retries: 10000
    temperature: 0

consultant_settings:
  max_rounds: 3        
  word_limit: 300


debaters:
  first:
    anthropic:
      name: "Debater A"
      provider: "anthropic"
      model: "claude-3-5-sonnet-20241022"
      temperature: 0.2
      max_retries: 300000
    openai:
      name: "Debater A"
      provider: "openai"
      model: "gpt-4o"
      temperature: 0.2
      max_retries: 300000
    sglang:
      name: "Debater A"
      provider: "sglang"
      model: "Qwen/Qwen2.5-7B-Instruct"
      port: 30005
      temperature: 0.2
      max_retries: 300000
    azure:
      name: "Debater A"
      provider: "azure"
      model: "DeepSeek-R1"
      endpoint: "https://DeepSeek-R1-rgchv.eastus.models.ai.azure.com"
      temperature: 0.2
      max_retries: 300000
  
  second:
    anthropic:
      name: "Debater B"
      provider: "anthropic"
      model: "claude-3-5-sonnet-20241022"
      temperature: 0.2
      max_retries: 300000
    openai:
      name: "Debater B"
      provider: "openai"
      model: "gpt-4o"
      temperature: 0.2
      max_retries: 300000 
    sglang:
      name: "Debater B"
      provider: "sglang"
      model: "Qwen/Qwen2.5-7B-Instruct"
      port: 30005
      temperature: 0.2
      max_retries: 300000
    azure:
      name: "Debater B"
      provider: "azure"
      model: "DeepSeek-R1"
      endpoint: "https://DeepSeek-R1-rgchv.eastus.models.ai.azure.com"
      temperature: 0.2
      max_retries: 300000


debate_judge:
  anthropic:
    name: "Debate Judge"
    provider: "anthropic"
    model: "claude-3-5-sonnet-20241022"
    temperature: 0
    max_retries: 300000
  openai:
    name: "Debate Judge"
    provider: "openai"
    model: "gpt-4o"
    temperature: 0
    max_retries: 300000
  sglang:
    name: "Debate Judge"
    provider: "sglang"
    model: "Qwen/Qwen2.5-7B-Instruct"
    port: 30005
    temperature: 0
    max_retries: 300000
  azure:
    name: "Debate Judge"
    provider: "azure"
    model: "DeepSeek-R1"
    endpoint: "https://DeepSeek-R1-rgchv.eastus.models.ai.azure.com"
    temperature: 0
    max_retries: 300000


debater_settings:
  max_rounds: 3        
  word_limit: 150




# data:
#   # Main directory where consultancy data will be saved
#   consultancy_saved_data_dir: "/Users/salman/Desktop/Project/debate/llm_debate/debate-salman/debate-final/src/main/saved-data/nov-26/output_consultancy"      